### ISSUE TITLE
Dynamically change region

### ISSUE THREAD

**Issue by natinusala** [Blizzard/passport-bnet#11]
How do I change the region dynamically ? I would like to ask for my users their region, and login to the appropriate server. I don't see a way to provide a region parameter when using Passport's authentication method, neither do I see a way to have multiple strategies, one for each region. 

Could you help me ?

**Comment by voidpirate** [comment]
@natinusala 
Although the readme doesn't include an example of `region`, you can still pass it in the constructor.

**Comment by blizz-aurifex** [comment]
It's probably best to ask this kind of question on our [API forums](http://us.battle.net/forums/en/bnet/15051532/index) as we don't closely watch the repo's activity. 

Long story short, you don't dynamically change region. Instead, you might want to try instantiating one instance of `passport-bnet` for each region you need to support. You can specify region using the `region` property of constructor's options object as @voidpirate noted.
