### ISSUE TITLE
Invalid request errors

### ISSUE THREAD

**Issue by mbonig** [Blizzard/passport-bnet#13]
I'm getting invalid_request errors when using the module. I've done some Fiddler2 and seen the traffic and can see it hitting the bnet server, and then hitting the callback with:

http://localhost:3000/api/auth/bnet/callback?error=invalid_request&error_description=Internal%20server%20error

I'm not seeing anything in the dev portal about errors. 

The code has been working into the strategies that are part of the MEANjs boilerplate [https://github.com/meanjs/mean] and looks like:

```
var passport = require('passport');
var BnetStrategy = require('passport-bnet').Strategy;

module.exports = function (config) {
    // Use the BnetStrategy within Passport.
    passport.use(new BnetStrategy({
        clientID: config.bnet.clientID,
        clientSecret: config.bnet.clientSecret,
        callbackURL: config.bnet.callbackURL
    }, function (accessToken, refreshToken, profile, done) {

        console.log(profile);
        // Set the provider data and include tokens
        var providerData = profile._json;
        providerData.accessToken = accessToken;
        providerData.refreshToken = refreshToken;

        // Create the user OAuth profile
        var providerUserProfile = {
            firstName: profile.name.givenName,
            lastName: profile.name.familyName,
            displayName: profile.displayName,
            email: profile.emails ? profile.emails[0].value : undefined,
            username: profile.username || generateUsername(profile),
            profileImageURL: undefined,
            provider: 'bnet',
            providerIdentifierField: 'id',
            providerData: providerData
        };

        // Save the user OAuth profile
        users.saveOAuthUserProfile(req, providerUserProfile, done);

        function generateUsername(profile) {
            var username = '';

            if (profile.emails) {
                username = profile.emails[0].value.split('@')[0];
            } else if (profile.name) {
                username = profile.name.givenName[0] + profile.name.familyName;
            }

            return username.toLowerCase() || undefined;
        }

    }));
};


```

Any thoughts on how I can get more information about the error. Or what might be going on?

Thanks
M

**Comment by mbonig** [comment]
I'm closing this issue. No problems with this module or bnet directly, just that I wasn't using an https redirect and it seems to be pretty undocumented that you need it.

**Comment by blizz-aurifex** [comment]
Well then, it looks like we should improve the docs. IMO it would be best to provide it in the actual signup page itself, but unfortunately we have limited control over the content of that page. So failing that, where would you have expected this information to be provided?

**Comment by mbonig** [comment]
Probably not here. I mean, I think on the README you could maybe add a little 'oh, btw,' but this is on Blizzard's Masher account, when setting up a callback url it should note that it has to be https.

**Comment by englercj** [comment]
Just to clarify OAuth2 protocol requires HTTPS, not just this module. We can add that information to the README so it is readily apparent to future users of the library.

**Comment by mbonig** [comment]
Correct, this isn't a problem with this module.

**Comment by tony-cocco** [comment]
I hate to resurrect a dead thread, but just spent a few hours trying to understand why I was getting these errors as well. Docs still don't reflect mandatory HTTPS callback. Configuration usage is also different on this repo's main README and the instructions on npm and the docs on the Bnet API site.

> Just to clarify OAuth2 protocol requires HTTPS...

I'm able to use OAuth2 with Github without having an HTTPS callback.
