### ISSUE TITLE
Scope wow.profile and list of all chars

### ISSUE THREAD

**Issue by rafalolszewskii** [Blizzard/passport-bnet#16]
Hi,
I've got my auth working, and I'm trying to retrieve per account list of characters in WoW. Where do I put the token I've got as a response from authentication ?

Best case scenario for me would be an working example to study on it. Although I have the API request code as follows:
```js
var request = require("request");

var options = { method: 'GET',
  url: 'https://eu.api.battle.net/wow/user/characters' };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

Where should I put the token ?

**Comment by blizz-aurifex** [comment]
You can provide the token using the `access_token` query parameter. For example, `https://us.api.battle.net/wow/user/characters?access_token=<TOKEN>`.

You might want to check out https://dev.battle.net/io-docs. The API docs are interactive -- you can see exactly what URL was requested, the response headers, and HTTP status code returned by the server.

( ᐛ )و

**Comment by rafalolszewskii** [comment]
Thank you @blizz-aurifex for quick answer.

I've already check the docs, there's no test bench for getting all characters. Although I will try to use your example and get back here if anything goes wrong. Will do that tomorrow, so please don't close the issue since I'm kind of yet getting used to Node.JS and I might need some help if that's alright.

**Comment by blizz-aurifex** [comment]
Happy to help. If you run into any issues you may also want to check out our forums at http://us.battle.net/forums/en/bnet/15051532/index. I'm pretty active there and we've got a few regulars that would also be glad to lend a hand.

**Comment by kelsin** [comment]
Due to limitations in the docs the test bench for oauth routes is under the heading "Community OAuth Profile APIs". You can test the wow characters one there.

**Comment by rafalolszewskii** [comment]
Alright, I've tested the function with ?access_token - it works perfectly. Now that may be not the main topic here, but I'm trying to pass the request to view, this is what I've come up with, but it doesn't work (neither the console.log before res.render())

```js
    app.get('/profile', isLoggedIn, function(req, res) {

        var request = require("request");
        var options = { method: 'GET',
          url: 'https://eu.api.battle.net/wow/user/characters',
          qs: { access_token: req.user.bnet.token } };

        request(options, function (err, respon, data) {
            if (err) throw new Error(err);
            res.render('profile.hbs', {
                user : req.user,
                wowChars : data
            });
        });
    });
```

**Comment by motorlatitude** [comment]
Does request automatically detect JSON and convert it because if it doesn't then you're trying to iterate through a string? I normally set request up as follows:
```javascript
request({
      url: "https://eu.api.battle.net/wow/user/characters?access_token=" + token,
      json: true
}, function (err, response, data) {
     if (err) throw new Error(err);
     res.render('profile.hbs', {
          user : req.user,
          wowChars : data
    });
});
```

**Comment by rafalolszewskii** [comment]
It wasn't, but tried and failed. `rawJson: JSON.stringify(data, 0, 2)` did the job, but now I'm struggling with getting for example name of my characters. Tried to loop with HBS, but failed again 😢

**Comment by motorlatitude** [comment]
When you say "tried and failed", what happened 😮 , did it output an error, if so what was it?
Sorry, I might just not be understanding you correctly, but it sounds like you're taking the JSON data from the request (which is returned as a string) and then using `JSON.stringify()` on it? That won't work if you want to iterate through the character data.

**Comment by rafalolszewskii** [comment]
The output was empty, I'm still a beginner to node.js and hbs that the cause of so many questions, although I'm doing my best to learn more each time I occur something.

Basic flow I want to do is to authenticate user - which is working fine, then on his profile get his WoW characters and display data such as character name, realm... for each character.

**Comment by motorlatitude** [comment]
Ooohhh, so the request isn't outputting any data, even when you use `console.log(data)` before the `res.render`? If so can you output the `console.log(response);` and copy it here, make sure to take out the token?

**Comment by rafalolszewskii** [comment]
If I do it this way:
```js
    app.get('/profile', isLoggedIn, function(req, res) {

        var request = require("request");
        var options = { method: 'GET',
          url: 'https://eu.api.battle.net/wow/user/characters',
          qs: { access_token: req.user.bnet.token } };

        request(options, function (err, respon, data1) {
            if (err) throw new Error(err);
            res.render('profile.hbs', {
                user : req.user,
                wowChars : data1
            });
        });
    });
```
and template tag like this
```hbs
<pre>{{ wowChars }}</pre>
```
it works fine (but the output is while characters endpoint), and I wan't to get the data such as name / realm of characters as I mentioned above.

**Comment by motorlatitude** [comment]
The reason for this is because when you output it like that it is in a String format, you can't while loop that. In order to do what you want, you have to parse the JSON, either by setting it as a parameter in the request (see above) or you can manually parse as well e.g.
```Javascript
app.get('/profile', isLoggedIn, function(req, res) {
    var request = require("request");
    var options = { 
        method: 'GET',
        url: 'https://eu.api.battle.net/wow/user/characters',
        qs: { access_token: req.user.bnet.token } 
    };

    request(options, function (err, respon, data1) {
        if (err) throw new Error(err);
        res.render('profile.hbs', {
            user : req.user,
            wowChars : JSON.parse(data1)
        });
    });
});
```
This way wowChars is an Object where you can then loop the characters. I'm not familiar with hbs but in JS the following would be what you want:
```Javascript
for(var i=0;i<wowChars.characters.length;i++){
    var name = wowChars.characters[i].name;
    //etc...
}
```
Quick look hat hbs, looks like this is what you would do:
```Handlebars
{{#each wowChars.characters}}
  <p>{{@index}}. {{this.name}}</p>
{{/each}}
```

**Comment by rafalolszewskii** [comment]
@motorlatitude this is entirely the solution to my case!!! I will love you till the end!

Thanks again, and have a great weekend guys!

**Comment by englercj** [comment]
You should be able to drop the `this` IIRC:

```
{{#each wowChars.characters}}
  <p>{{@index}}. {{name}}</p>
{{/each}}
```

**Comment by rafalolszewskii** [comment]
Indeed @englercj it works too, thank as well!

**Comment by blizz-aurifex** [comment]
Small nit pick: I'd recommend delegating JSON handling to Request library instead of doing it manually. So instead of this ...

```js
app.get('/profile', isLoggedIn, function(req, res) {
    var request = require("request");
    var options = { 
        method: 'GET',
        url: 'https://eu.api.battle.net/wow/user/characters',
        qs: { access_token: req.user.bnet.token } 
    };

    request(options, function (err, respon, data1) {
        if (err) throw new Error(err);
        res.render('profile.hbs', {
            user : req.user,
            wowChars : JSON.parse(data1)
        });
    });
});
```

You should do this
```js
app.get('/profile', isLoggedIn, function(req, res) {
    var request = require("request");
    var options = { 
        method: 'GET',
        json: true,
        url: 'https://eu.api.battle.net/wow/user/characters',
        qs: { access_token: req.user.bnet.token } 
    };

    request(options, function (err, respon, body) {
        if (err) throw new Error(err);
        res.render('profile.hbs', {
            user: req.user,
            wowChars: body
        });
    });
});
```

That's where I got tripped up when trying to help earlier -- I didn't realize your request response was a String.

**Comment by motorlatitude** [comment]
@blizz-aurifex yup, agree 100%. However @rafalolszewskii mentioned that letting the request library handle it didn't work for him, no clue why?

**Comment by blizz-aurifex** [comment]
@motorlatitude Ugh, I'm just missing all the salient details in this thread. Yep, he totally said it didn't work. My brain is too tired to venture a guess as to why. Regardless, it works now so whatever 😉

**Comment by motorlatitude** [comment]
@blizz-aurifex ha ha, don't worry about it, I'm too tired as well, NEED COFFEE! If it works back away and don't touch it 😛 .

**Comment by rafalolszewskii** [comment]
No clue at all why it didn't work. It clearly says even in request package docs that there is a option `json` to do that, anyway, it works as it should right now :)

**Comment by englercj** [comment]
@blizz-aurifex `Content-Type` set properly?

**Comment by blizz-aurifex** [comment]
@englercj On the API? I do believe so, yeah. More concretely, I was able to do it in my Express test app while I was testing ~1 hour ago.

**Comment by motorlatitude** [comment]
@englercj @blizz-aurifex The API definitely sets the `Content-Type` correctly and I also have it working in production and in a quick test I did as well, very weird...
