### ISSUE TITLE
Passing context around from .authenticate()

### ISSUE THREAD

**Issue by JoeRoddy** [Blizzard/passport-bnet#20]
Is there any way to pass data along that will be passed back on the callback?

For instance, a user has a userId in my app.  I would like to access the userId for my app in my callback and persist that user's battletag. 

Something like:

```
app.get("/auth/bnet/:userId", passport.authenticate("bnet", {userId: req.params.userId}));

app.get(
  "/auth/bnet/callback",
  passport.authenticate("bnet", { failureRedirect: "/" }),
  (req, res) => {
    const userId = req.someContextObject.userId;
    persistBattletagForUser(userId, req.user.battletag);
  }
);
```

I took a  look through the passport docs, and I can't really find what I'm looking for (but I can be really dense).  Or perhaps I could store it in the passport session somehow?

Sorry if this is the wrong place to ask this.

**Comment by maael** [comment]
You can get the `req` object in your strategy, which is probably where you would want to be doing this, if you give your strategy the `passReqToCallback: true` option (common to all oauth passport strategies).

A rough quick example would be defining your `BnetStrategy` something like:

```
  passport.use(new BnetStrategy({
    clientID: BLIZZARD_KEY,
    clientSecret: BLIZZARD_SECRET,
    callbackURL: `${PROTOCOL}://${HOST}:${PORT}/auth/bnet/callback`,
    region: 'eu',
    scope: [ 'wow.profile' ],
    passReqToCallback: true
  }, (req, accessToken, refreshToken, profile, done) => {
    console.log(req.user, accessToken, profile)
    // probably do your persistBattletagForUser here using the profile object
    return done(null, profile)
  }))
```
Even if this isn't perfect, it should point you in the right direction of finding an answer hopefully.

**Comment by JoeRoddy** [comment]
Thanks a lot @maael  :D
